[Unit]
Documentation=file:///opt/ingress/README.md
ConditionPathExists=/var/lib/ingress/trash

[Path]
PathChanged=
PathExistsGlob=/var/lib/ingress/trash/*.json
DirectoryNotEmpty=/var/lib/ingress/trash
