#!/usr/bin/env python3
# DEPRECATED: Use ./dev/bin/metricsctl instead.
#
# This shim delegates to the canonical entrypoint at dev/bin/metricsctl.
# It will be removed after the deprecation period (see Issue #8).

import os
import sys
from pathlib import Path

sys.stderr.write(
    "[DEPRECATED] ./metricsctl is deprecated; use ./dev/bin/metricsctl\n"
)

_repo = Path(__file__).resolve().parent
_launcher = str(_repo / "dev" / "bin" / "metricsctl")

os.execv(_launcher, [_launcher, *sys.argv[1:]])

