"""Read-only sync import from permanent library hash caches.

This module imports advisory SHA1 data from `.hashes.sha1` files generated by
`nightfall-immich-rmdups.sh`. When a cache file is missing, stale, or invalid,
the importer re-hashes the directory contents in-memory for import only and
never rewrites files inside the library.
"""

from __future__ import annotations

import hashlib
import json
import re
import sqlite3
from dataclasses import dataclass
from pathlib import Path

from .config import AppConfig
from .domain.registry import Registry

DIRECTORY_HASH_HEADER_RE = re.compile(r"^DIRECTORY_HASH\s+([0-9a-fA-F]{40})$")
SHA1_ROW_RE = re.compile(r"^([0-9a-fA-F]{40})\s+[ *](.+)$")
EXTERNAL_HASH_CACHE_SCOPE = "__library__"
IGNORED_FILENAMES = {".hashes.sha1"}
IGNORED_BASENAMES_CASEFOLD = {"thumbs.db"}


class SyncImportError(RuntimeError):
    """Raised when sync-import configuration or parsing fails."""


@dataclass(frozen=True)
class ImportedHashEntry:
    """One imported advisory hash row derived from cache or fallback rehash."""

    source_relpath: str
    sha1: str


@dataclass(frozen=True)
class DirectoryImportPlan:
    """Import plan for one library directory."""

    directory: Path
    entries: tuple[ImportedHashEntry, ...]
    source: str
    invalid_line_count: int = 0


@dataclass(frozen=True)
class SyncImportSummary:
    """Summary returned by one sync-import run."""

    directories_scanned: int
    cache_files_used: int
    directories_rehashed: int
    imported_rows: int
    skipped_rows: int
    invalid_lines: int
    dry_run: bool


def run_sync_import(app_config: AppConfig, *, dry_run: bool) -> SyncImportSummary:
    """Import advisory hashes from the configured permanent-library root."""

    if not app_config.core.sync_hash_import_enabled:
        raise SyncImportError("sync-import is disabled in [core]")

    library_root = app_config.core.sync_hash_import_path
    if not library_root.exists():
        raise SyncImportError(f"sync-import path does not exist: {library_root}")
    if not library_root.is_dir():
        raise SyncImportError(f"sync-import path is not a directory: {library_root}")

    registry = Registry(app_config.core.registry_path)
    registry.initialize()

    directories = [library_root]
    directories.extend(sorted(path for path in library_root.rglob("*") if path.is_dir()))

    cache_files_used = 0
    directories_rehashed = 0
    imported_rows = 0
    skipped_rows = 0
    invalid_lines = 0

    for directory in directories:
        plan = build_directory_import_plan(
            library_root=library_root,
            directory=directory,
            hash_glob=app_config.core.sync_hash_import_glob,
        )
        if plan.source == "cache":
            cache_files_used += 1
        elif plan.source == "rehash":
            directories_rehashed += 1
        invalid_lines += plan.invalid_line_count

        for entry in plan.entries:
            if _external_hash_cache_row_exists(
                registry.db_path,
                source_relpath=entry.source_relpath,
                hash_value=entry.sha1,
            ):
                skipped_rows += 1
                continue

            imported_rows += 1
            if dry_run:
                continue

            registry.upsert_external_hash_cache(
                account_name=EXTERNAL_HASH_CACHE_SCOPE,
                source_relpath=entry.source_relpath,
                hash_algo="sha1",
                hash_value=entry.sha1,
                verified_sha256=None,
            )
            registry.append_audit_event(
                sha256=None,
                account_name=EXTERNAL_HASH_CACHE_SCOPE,
                action="sync_import",
                reason="library_hash_import",
                details_json=json.dumps(
                    {"source_relpath": entry.source_relpath, "hash_algo": "sha1"},
                    sort_keys=True,
                ),
                actor="sync_import",
            )

    return SyncImportSummary(
        directories_scanned=len(directories),
        cache_files_used=cache_files_used,
        directories_rehashed=directories_rehashed,
        imported_rows=imported_rows,
        skipped_rows=skipped_rows,
        invalid_lines=invalid_lines,
        dry_run=dry_run,
    )


def build_directory_import_plan(
    *,
    library_root: Path,
    directory: Path,
    hash_glob: str,
) -> DirectoryImportPlan:
    """Build import plan for a single directory using cache or fallback rehash."""

    cache_path = directory / hash_glob
    if cache_path.exists():
        parsed_entries, invalid_line_count = _parse_hash_cache_file(
            cache_path=cache_path,
            library_root=library_root,
            directory=directory,
        )
        if parsed_entries is not None:
            return DirectoryImportPlan(
                directory=directory,
                entries=parsed_entries,
                source="cache",
                invalid_line_count=invalid_line_count,
            )
        return DirectoryImportPlan(
            directory=directory,
            entries=_rehash_directory_entries(library_root=library_root, directory=directory),
            source="rehash",
            invalid_line_count=invalid_line_count,
        )

    return DirectoryImportPlan(
        directory=directory,
        entries=_rehash_directory_entries(library_root=library_root, directory=directory),
        source="rehash",
        invalid_line_count=0,
    )


def _parse_hash_cache_file(
    *,
    cache_path: Path,
    library_root: Path,
    directory: Path,
) -> tuple[tuple[ImportedHashEntry, ...] | None, int]:
    """Parse one `.hashes.sha1` file according to the producer contract."""

    try:
        lines = cache_path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return None, 1

    if not lines:
        return None, 1

    if DIRECTORY_HASH_HEADER_RE.fullmatch(lines[0].strip()) is None:
        return None, 1

    invalid_line_count = 0
    parsed: list[ImportedHashEntry] = []
    seen_paths: set[Path] = set()

    for raw_line in lines[1:]:
        match = SHA1_ROW_RE.fullmatch(raw_line.rstrip("\n"))
        if match is None:
            invalid_line_count += 1
            return None, invalid_line_count

        sha1 = match.group(1).lower()
        file_path = Path(match.group(2))
        if not file_path.is_absolute():
            invalid_line_count += 1
            return None, invalid_line_count
        if file_path.parent != directory:
            invalid_line_count += 1
            return None, invalid_line_count
        if _is_ignored_file(file_path):
            invalid_line_count += 1
            return None, invalid_line_count
        if not file_path.exists() or not file_path.is_file():
            invalid_line_count += 1
            return None, invalid_line_count

        seen_paths.add(file_path)
        parsed.append(
            ImportedHashEntry(
                source_relpath=str(file_path.relative_to(library_root)),
                sha1=sha1,
            )
        )

    actual_files = set(_iter_importable_files(directory))
    if actual_files != seen_paths:
        invalid_line_count += 1
        return None, invalid_line_count

    return tuple(parsed), invalid_line_count


def _rehash_directory_entries(*, library_root: Path, directory: Path) -> tuple[ImportedHashEntry, ...]:
    """Compute advisory SHA1 rows directly from library files without writing caches."""

    entries: list[ImportedHashEntry] = []
    for file_path in _iter_importable_files(directory):
        entries.append(
            ImportedHashEntry(
                source_relpath=str(file_path.relative_to(library_root)),
                sha1=_sha1_file(file_path),
            )
        )
    return tuple(entries)


def _iter_importable_files(directory: Path) -> list[Path]:
    """Return immediate files eligible for advisory hash import."""

    return sorted(
        (
            path
            for path in directory.iterdir()
            if path.is_file() and not _is_ignored_file(path)
        ),
        key=lambda path: path.name,
    )


def _is_ignored_file(path: Path) -> bool:
    """Return True for non-content files excluded by the producer script."""

    return (
        path.name in IGNORED_FILENAMES
        or path.name.casefold() in IGNORED_BASENAMES_CASEFOLD
    )


def _sha1_file(path: Path, chunk_size: int = 64 * 1024) -> str:
    """Return SHA1 for one file using streaming reads."""

    digest = hashlib.sha1()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(chunk_size)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def _external_hash_cache_row_exists(
    db_path: Path,
    *,
    source_relpath: str,
    hash_value: str,
) -> bool:
    """Return True when identical advisory hash row already exists."""

    with sqlite3.connect(db_path) as conn:
        row = conn.execute(
            """
            SELECT 1
            FROM external_hash_cache
            WHERE account_name = ? AND source_relpath = ? AND hash_algo = 'sha1' AND hash_value = ?
            LIMIT 1
            """,
            (EXTERNAL_HASH_CACHE_SCOPE, source_relpath, hash_value),
        ).fetchone()
    return row is not None